#' Filter environmental outliers from presence records using Mahalanobis distance
#'
#' Identifies and removes presence records that are environmental outliers
#' based on their Mahalanobis distance (D^2) to the centroid of the presence
#' cloud in environmental space. Only presence records (`presence == "1"`) are
#' evaluated; pseudo-absences are always retained unchanged.
#'
#' The threshold is derived from the chi-squared distribution:
#' `qchisq(threshold, df = length(vars_cov))`. A record is flagged as an
#' outlier when its D^2 exceeds this value. The default `threshold = 0.975`
#' corresponds to the standard 97.5th percentile used in SDM practice.
#'
#' @param pa         An `sf` object produced by [h3sdm_pa_from_records()] or
#'                   [h3sdm_pa()], containing a `presence` column with values
#'                   `"1"` (presence) and `"0"` (pseudo-absence), plus numeric
#'                   covariate columns.
#' @param vars_cov   Character vector of covariate column names to use for the
#'                   Mahalanobis distance calculation. Typically the bioclimatic
#'                   variables (e.g. CHELSA). If `NULL` (default), all numeric
#'                   columns except `h3_address`, `presence`, `x`, and `y` are
#'                   used automatically.
#' @param threshold  Numeric in (0, 1). Percentile of the chi-squared
#'                   distribution used as the outlier threshold.
#'                   Default `0.975`.
#'
#' @return A list with four elements:
#' \describe{
#'   \item{`pa_clean`}{`sf` object -- the input PA dataset with outlier
#'         presences removed. Pseudo-absences are untouched.}
#'   \item{`outliers_df`}{`data.frame` with the removed records and an
#'         additional column `mahal_d2` with their D^2 values. Empty
#'         `data.frame` if no outliers were detected.}
#'   \item{`n_removed`}{Integer. Number of presence records removed.}
#'   \item{`threshold_d2`}{Numeric. The D^2 threshold value used
#'         (`qchisq(threshold, df = k)`).}
#' }
#'
#' @details
#' **Why only presences?** Pseudo-absences are algorithmically generated by
#' `h3sdm` and carry no georeferencing or identification error. Filtering them
#' would remove points at the environmental periphery -- exactly those most
#' informative for defining the species niche boundary.
#'
#' **Singular covariance matrix:** When presences are too few or covariates are
#' perfectly collinear the covariance matrix becomes singular and cannot be
#' inverted. In that case the function returns the original PA unchanged with a
#' warning.
#'
#' **Relationship with AOA:** The AOA (see [h3sdm_aoa()]) evaluates prediction
#' reliability *after* training. This function improves *input data quality*
#' *before* training. Both are complementary: an unfiltered outlier can
#' artificially expand the AOA into ecologically implausible areas.
#'
#' @seealso [h3sdm_pa_from_records()], [h3sdm_aoa()]
#'
#' @examples
#' \dontrun{
#' # After generating the PA dataset:
#' pa <- h3sdm_pa_from_records(records, aoi_sf, res = 7L,
#'                              predictors_sf = cov_actual)
#'
#' # Auto-detect covariates and filter with default threshold (97.5%)
#' result <- h3sdm_filter_outliers(pa)
#'
#' # Inspect removed records
#' result$outliers_df
#'
#' # Use the clean PA for modeling
#' dat <- h3sdm_data(result$pa_clean, pred_sf)
#'
#' # Custom covariate selection and stricter threshold
#' result2 <- h3sdm_filter_outliers(pa,
#'                                   vars_cov  = c("bio1", "bio12", "bio15"),
#'                                   threshold = 0.95)
#' }
#'
#' @export
h3sdm_filter_outliers <- function(pa, vars_cov = NULL, threshold = 0.975) {

  # -- Argument validation ------------------------------------------------------
  if (!inherits(pa, "sf")) {
    stop("`pa` must be an sf object.")
  }
  if (!"presence" %in% names(pa)) {
    stop("`pa` must contain a `presence` column with values '1' and '0'.")
  }
  if (!is.numeric(threshold) || threshold <= 0 || threshold >= 1) {
    stop("`threshold` must be a numeric value in (0, 1).")
  }

  # -- Auto-detect covariates ---------------------------------------------------
  if (is.null(vars_cov)) {
    excluir  <- c("h3_address", "presence", "x", "y")
    pa_df    <- sf::st_drop_geometry(pa)
    vars_cov <- setdiff(names(pa_df), excluir)
    vars_cov <- vars_cov[vapply(pa_df[, vars_cov, drop = FALSE],
                                is.numeric, logical(1))]
  }

  if (length(vars_cov) == 0) {
    warning("[h3sdm_filter_outliers] No numeric covariate columns found. ",
            "Returning PA unchanged.")
    return(.outliers_no_filter(pa))
  }

  # -- Extract presences --------------------------------------------------------
  idx_pres <- which(pa$presence == "1")

  if (length(idx_pres) < (length(vars_cov) + 2L)) {
    warning("[h3sdm_filter_outliers] Too few presences to compute Mahalanobis ",
            "distance reliably. Returning PA unchanged.")
    return(.outliers_no_filter(pa))
  }

  pres_df   <- sf::st_drop_geometry(pa)[idx_pres, vars_cov, drop = FALSE]
  completos <- stats::complete.cases(pres_df)

  if (sum(completos) < (length(vars_cov) + 2L)) {
    warning("[h3sdm_filter_outliers] Too few complete presence cases after ",
            "removing NAs. Returning PA unchanged.")
    return(.outliers_no_filter(pa))
  }

  pres_completa <- pres_df[completos, , drop = FALSE]

  # -- Centroid and covariance matrix -------------------------------------------
  centro <- colMeans(pres_completa)
  cov_m  <- tryCatch(
    stats::cov(pres_completa),
    error = function(e) NULL
  )

  if (is.null(cov_m) || det(cov_m) < .Machine$double.eps) {
    warning("[h3sdm_filter_outliers] Singular covariance matrix -- ",
            "covariates may be perfectly collinear. Returning PA unchanged.")
    return(.outliers_no_filter(pa))
  }

  # -- Mahalanobis distance -----------------------------------------------------
  d2        <- stats::mahalanobis(pres_completa, center = centro, cov = cov_m)
  umbral_d2 <- stats::qchisq(threshold, df = length(vars_cov))

  # Indices of outliers in pa
  idx_completos_en_pa <- idx_pres[completos]
  idx_outliers        <- idx_completos_en_pa[d2 > umbral_d2]

  # -- Build result -------------------------------------------------------------
  outliers_df <- if (length(idx_outliers) > 0L) {
    df          <- sf::st_drop_geometry(pa)[idx_outliers, , drop = FALSE]
    df$mahal_d2 <- d2[d2 > umbral_d2]
    df[order(df$mahal_d2, decreasing = TRUE), ]
  } else {
    data.frame()
  }

  pa_clean <- if (length(idx_outliers) > 0L) pa[-idx_outliers, ] else pa

  list(
    pa_clean     = pa_clean,
    outliers_df  = outliers_df,
    n_removed    = length(idx_outliers),
    threshold_d2 = umbral_d2
  )
}

# -- Internal helper ----------------------------------------------------------
.outliers_no_filter <- function(pa) {
  list(
    pa_clean     = pa,
    outliers_df  = data.frame(),
    n_removed    = 0L,
    threshold_d2 = NA_real_
  )
}
