#' @name h3sdm_recipe
#' @title Create a tidymodels recipe for H3-based SDMs
#' @description
#' Prepares an `sf` object with H3 hexagonal data for modeling with the
#' `tidymodels` ecosystem. Extracts centroid coordinates, assigns appropriate
#' roles to the variables automatically, and returns a ready-to-use recipe for
#' modeling species distributions.
#'
#' @param data An `sf` object, typically the output of `h3sdm_data()`,
#'   including species presence-absence or count data, H3 addresses, and
#'   environmental predictors. The geometry must be of type `MULTIPOLYGON`.
#' @param response_col `character` Name of the column to use as the outcome
#'   (response variable). Default `"presence"` for presence/absence models.
#'   Use `"count"` when working with count data generated by
#'   `h3sdm_count_from_records()`.
#'
#' @details
#' This function prepares spatial H3 grid data for species distribution modeling:
#' \itemize{
#'   \item Extracts centroid coordinates (`x` and `y`) from MULTIPOLYGON geometries.
#'   \item Removes the geometry column to create a purely tabular dataset for tidymodels.
#'   \item Assigns roles to columns:
#'     \itemize{
#'       \item `response_col` → `"outcome"` (target variable)
#'       \item `h3_address` → `"id"` (used for joining predictions later)
#'       \item `x` and `y` → `"spatial_predictor"`
#'     }
#'   \item All other columns are assigned `"predictor"` role.
#' }
#'
#' @return A `tidymodels` recipe object (class `"h3sdm_recipe"`) ready for modeling.
#'
#' @examples
#' \dontrun{
#' # Presence/absence model (default)
#' sdm_recipe <- h3sdm_recipe(combined_data)
#'
#' # Count-based model
#' sdm_recipe <- h3sdm_recipe(combined_data, response_col = "count")
#' }
#'
#' @importFrom recipes recipe
#' @importFrom dplyr mutate
#' @importFrom sf st_coordinates st_centroid st_geometry st_drop_geometry
#'
#' @export
h3sdm_recipe <- function(data, response_col = "presence") {
  if (!inherits(data, "sf")) stop("data must be an sf object.")

  centroids <- sf::st_centroid(sf::st_geometry(data))
  coords <- sf::st_coordinates(centroids)

  data_no_geom <- data %>%
    sf::st_drop_geometry() %>%
    dplyr::mutate(
      x = coords[, 1],
      y = coords[, 2]
    )

  if (!response_col %in% names(data_no_geom)) {
    stop(
      "Column '", response_col, "' not found in data. ",
      "Use response_col = 'count' if you are working with count data."
    )
  }

  all_vars <- names(data_no_geom)
  roles <- rep("predictor", length(all_vars))
  roles[all_vars == response_col]  <- "outcome"
  roles[all_vars == "h3_address"]  <- "id"
  roles[all_vars == "x"]           <- "spatial_predictor"
  roles[all_vars == "y"]           <- "spatial_predictor"

  rec <- recipes::recipe(
    x = data_no_geom,
    vars = all_vars,
    roles = roles,
    strings_as_factors = FALSE
  )

  class(rec) <- c("h3sdm_recipe", class(rec))
  return(rec)
}
