#' @name h3sdm_recipe_gam
#' @title Creates a 'recipe' object for Generalized Additive Models (GAM) in SDM
#'
#' @description
#' This function prepares an \code{sf} object for use in a Species Distribution
#' Model (SDM) workflow with the 'mgcv' GAM engine within the 'tidymodels'
#' ecosystem. Extracts centroid coordinates and assigns appropriate roles to
#' all variables, including the response variable and spatial coordinates.
#'
#' @param data An \code{sf} object containing the response variable,
#'   environmental predictors, and geometry (e.g., H3 hexagon polygons).
#' @param response_col \code{character} Name of the column to use as the outcome
#'   (response variable). Default \code{"presence"} for presence/absence models.
#'   Use \code{"count"} when working with count data generated by
#'   \code{h3sdm_count_from_records()}.
#'
#' @return A \code{recipe} object of class \code{h3sdm_recipe_gam},
#'   ready to be chained with additional preprocessing steps.
#'
#' @details
#' \strong{Assigned Roles:}
#' \itemize{
#'   \item \code{outcome}: the column specified in \code{response_col}.
#'   \item \code{id}: \code{"h3_address"} (cell identifier, not used for modeling).
#'   \item \code{predictor}: all other variables, including \code{x} and \code{y}
#'     for the GAM spatial smooth term (\code{s(x, y, bs = "tp")}).
#' }
#'
#' @family h3sdm_tools
#' @importFrom sf st_centroid st_geometry st_coordinates st_drop_geometry
#' @importFrom dplyr mutate
#' @importFrom recipes recipe
#'
#' @examples
#' \donttest{
#'   library(sf)
#'   library(recipes)
#'
#'   set.seed(42)
#'   n <- 20
#'
#'   pts <- sf::st_as_sf(
#'     data.frame(
#'       h3_address   = paste0("hex_", seq_len(n)),
#'       presence     = sample(0:1, n, replace = TRUE),
#'       count        = sample(0:9, n, replace = TRUE),
#'       bio1_temp    = runif(n, 15, 30),
#'       bio12_precip = runif(n, 500, 3000)
#'     ),
#'     geometry = sf::st_sfc(
#'       lapply(seq_len(n), function(i) {
#'         sf::st_point(c(runif(1, -84.5, -83.5), runif(1, 9.5, 10.5)))
#'       }),
#'       crs = 4326
#'     )
#'   )
#'
#'   # Presence/absence model (default)
#'   gam_rec <- h3sdm_recipe_gam(pts)
#'
#'   # Count-based model
#'   gam_rec <- h3sdm_recipe_gam(pts, response_col = "count")
#' }
#'
#' @export
h3sdm_recipe_gam <- function(data, response_col = "presence") {
  if (!inherits(data, "sf")) stop("data must be an sf object.")

  centroids <- sf::st_centroid(sf::st_geometry(data))
  coords <- sf::st_coordinates(centroids)

  data_no_geom <- data %>%
    sf::st_drop_geometry() %>%
    dplyr::mutate(
      x = coords[, 1],
      y = coords[, 2]
    )

  if (!response_col %in% names(data_no_geom)) {
    stop(
      "Column '", response_col, "' not found in data. ",
      "Use response_col = 'count' if you are working with count data."
    )
  }

  all_vars <- names(data_no_geom)
  roles <- rep("predictor", length(all_vars))
  roles[all_vars == response_col] <- "outcome"
  roles[all_vars == "h3_address"] <- "id"

  rec <- recipes::recipe(
    x = data_no_geom,
    vars = all_vars,
    roles = roles,
    strings_as_factors = FALSE
  )

  class(rec) <- c("h3sdm_recipe_gam", class(rec))
  return(rec)
}
